### ISSUE TITLE
Error when updating to 0.13.2

### ISSUE THREAD

**Issue by kingbri1** [museun/twitchchat#199]
Hi, I'm getting this error and just recently updated the lib to 0.13.2 in my cargo.toml

[https://del.dog/bestotocke.txt](https://del.dog/bestotocke.txt)

**Comment by kingbri1** [comment]
Ok, so I figured out the reason, I have to include futures-lite in my cargo.toml and cargo check works. Can you include this within dependencies?

**Comment by museun** [comment]
It seems futures-lite feature gated those traits in a recent update.

I don't know why the tests didn't catch it. I've fixed it in 36ccccc

**Comment by tAq5Z6eE** [comment]
It looks like the same error has been re-introduced by https://github.com/museun/twitchchat/commit/9f33ac41149af6bfabc6bf02446d903590fa2fd1.

**Comment by museun** [comment]
Are you using (atleast) `features = [ "async" ]`?

**Comment by tAq5Z6eE** [comment]
Yes, I’m using 
```toml
[dependencies]
twitchchat = { version = "0.14.3", features = ["async", "tokio", "tokio-util"] }
```
in my Cargo.toml.
